# Generated by Django 6.0.2 on 2026-05-10 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('cost_index', models.DecimalField(decimal_places=2, max_digits=6)),
                ('popularity_score', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-popularity_score', 'name'],
                'indexes': [models.Index(fields=['country'], name='destination_country_57f51c_idx'), models.Index(fields=['region'], name='destination_region_405ce2_idx'), models.Index(fields=['-popularity_score'], name='destination_popular_b9b798_idx')],
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('sightseeing', 'Sightseeing'), ('food', 'Food'), ('adventure', 'Adventure'), ('other', 'Other')], default='other', max_length=20)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='destinations.city')),
            ],
            options={
                'ordering': ['city__name', 'name'],
                'indexes': [models.Index(fields=['category'], name='destination_categor_4bca51_idx'), models.Index(fields=['estimated_cost'], name='destination_estimat_b44a13_idx')],
            },
        ),
    ]
