# Generated by Django 5.2.11 on 2026-05-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='cost_index',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
