# Generated by Django 6.0.2 on 2026-05-10 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_activity_image'),
        ('destinations', '0002_alter_city_cost_index_alter_city_region'),
    ]

    operations = [
    ]
