# Generated by Django 6.0.2 on 2026-05-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_city_latitude_city_longitude'),
        ('destinations', '0003_merge_20260510_0522'),
    ]

    operations = [
    ]
