# Generated by Django 6.0.2 on 2026-05-10 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_merge_20260510_0540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='image',
        ),
        migrations.RemoveField(
            model_name='city',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='city',
            name='longitude',
        ),
    ]
