# Generated by Django 5.2.11 on 2026-05-10 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='trips.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transport', 'Transport'), ('stay', 'Stay'), ('food', 'Food'), ('activities', 'Activities'), ('misc', 'Miscellaneous')], default='misc', max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='trips.stop')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='budget.tripbudget')),
            ],
            options={
                'ordering': ['date', 'category'],
            },
        ),
        migrations.AddIndex(
            model_name='tripbudget',
            index=models.Index(fields=['trip'], name='budget_trip_trip_id_f06299_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['budget', 'category'], name='budget_expe_budget__50274f_idx'),
        ),
    ]
