# Generated by Django 5.2.11 on 2026-05-10 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='qty_label',
            field=models.CharField(blank=True, default='', help_text='e.g. 3 nights, 2 tickets', max_length=50),
        ),
        migrations.AddField(
            model_name='expense',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='expense',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('generated_date', models.DateField(auto_now_add=True)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=10)),
                ('budget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='budget.tripbudget')),
            ],
            options={
                'indexes': [models.Index(fields=['invoice_id'], name='budget_invo_invoice_9621a4_idx')],
            },
        ),
    ]
