# Generated by Django 6.0.2 on 2026-05-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language_preference',
            field=models.CharField(blank=True, default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_cities',
            field=models.ManyToManyField(blank=True, related_name='saved_by_profiles', to='destinations.city'),
        ),
    ]
