# Generated by Django 6.0.2 on 2026-05-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_activity_image'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stopactivity',
            constraint=models.UniqueConstraint(fields=('stop', 'activity'), name='unique_activity_per_stop'),
        ),
    ]
