# Generated by Django 6.0.2 on 2026-05-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_stopactivity_unique_activity_per_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='transport_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
